name: MysticShards
version: 1.0
api-version: 1.21
main: com.nick.shards.MysticShards

commands:
  shards:
    description: shard command for messing with shard stuff
    permission: shards.commands.shards
    usage: /shards set <player> <shard>
