name: MysticShards
version: 1.0
api-version: 1.21
main: com.nick.shards.MysticShards

commands:
  shards:
    description: Base command for Mystic Shards
    permission: shards.commands.shards
    usage: /shards <operation> <player> <shard>